name: Fast Build v2rayNG Fork
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew
        working-directory: ./V2rayNG

      - name: Fetch Precompiled Core (libv2ray.aar)
        run: |
          mkdir -p V2rayNG/app/libs
          curl -L -o V2rayNG/app/libs/libv2ray.aar https://github.com/2dust/AndroidLibXrayLite/releases/latest/download/libv2ray.aar

      - name: Build Fast Release APK
        # -Pandroid.injected.build.abi собирает ТОЛЬКО под arm64, срезая 70% времени сборки
        run: ./gradlew assembleRelease -Pandroid.injected.build.abi=arm64-v8a -x test -x lint
        working-directory: ./V2rayNG

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: v2rayNG-fast-release
          path: V2rayNG/app/build/outputs/apk/release/*.apk
